Disable more Spire processing.

diff --git a/src/CMake/Utils/processSCIRunLibs.sh.in b/src/CMake/Utils/processSCIRunLibs.sh.in
--- a/src/CMake/Utils/processSCIRunLibs.sh.in
+++ b/src/CMake/Utils/processSCIRunLibs.sh.in
@@ -103,13 +103,13 @@ if (( $? != 0 )); then
   exit 255
 fi
 
-COMMAND=`otool -L $EXECUTABLE_APP_NAME | @SED@ -n 's:@SPIRE_LIBRARY_DIR@/:& :p' | @AWK@ -v lib=$EXECUTABLE_APP_NAME '{print "install_name_tool -change "$1$2" "$2" " lib }'`
-echo "${COMMAND}"
-sh -c "${COMMAND}"
-if (( $? != 0 )); then
-  echo "${COMMAND} failed. Quitting."
-  exit 255
-fi
+#COMMAND=`otool -L $EXECUTABLE_APP_NAME | @SED@ -n 's:@SPIRE_LIBRARY_DIR@/:& :p' | @AWK@ -v lib=$EXECUTABLE_APP_NAME '{print "install_name_tool -change "$1$2" "$2" " lib }'`
+#echo "${COMMAND}"
+#sh -c "${COMMAND}"
+#if (( $? != 0 )); then
+#  echo "${COMMAND} failed. Quitting."
+#  exit 255
+#fi
 
 COMMAND=`otool -L $EXECUTABLE_APP_NAME | @SED@ -n 's:[^/][^/]*lib[A-z0-9_.]*.dylib:&:p' | @AWK@ -v lib=$EXECUTABLE_APP_NAME '{print "install_name_tool -change "$1" @executable_path/lib/"$1" " lib }'`
 echo "${COMMAND}"
